name: Playit RDP Tunnel Linux
on:
  workflow_dispatch:
jobs:
  setup-rdp-tunnel:
    runs-on: ubuntu-22.04
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xrdp xfce4 xfce4-goodies
        sudo systemctl enable xrdp
        sudo systemctl start xrdp
        echo "xfce4-session" > ~/.xsession
    - name: Create and Configure User
      run: |
        sudo useradd -m -s /bin/bash runneradmin
        echo "runner:fiki123" | sudo chpasswd  # Password di-hardcode
    - name: Configure Firewall
      run: |
        sudo ufw allow 3389
        sudo ufw reload
    - name: Download and Install Playit
      run: |
        wget https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-linux-x86_64 -O ~/playit
        chmod +x ~/playit
    - name: Start Playit and Set Up RDP Tunnel
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PL }}
      run: |
        ~/playit --secret $PLAYIT_AUTH_KEY &
        sleep 5
        if ! pgrep -x "playit" > /dev/null; then
          echo "Playit failed to start"
          exit 1
        fi
    - name: Keep the GitHub Action Runner Alive
      run: |
        sleep 11800
