name: Playit RDP Tunnel

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Download and Install Playit
      run: |
        wget -O ~/playit https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-linux-amd64
        chmod +x ~/playit
        sleep 5

    - name: Install XRDP and Desktop Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y xrdp xfce4 xfce4-goodies
        sudo systemctl enable xrdp
        sudo systemctl start xrdp
        echo "runner:p@ssw0rd123" | sudo chpasswd  # Ganti dengan password yang lebih aman
        echo xfce4-session > ~/.xsession
        sudo ufw allow 3389

    - name: Start Playit and Set Up RDP Tunnel
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PL }} 
      run: |
        ~/playit --secret $PLAYIT_AUTH_KEY &
        sleep 10

    - name: Keep the GitHub Action Runner Alive
      run: |
        echo "RDP running on port 3389, check Playit dashboard for tunnel address"
        sleep 11800
