name: Playit RDP Tunnel (Linux)

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: ubuntu-latest

    steps:
    - name: Update & Install Desktop + RDP Server
      run: |
        sudo apt update
        sudo apt install -y xrdp xfce4 xfce4-goodies
        echo xfce4-session > ~/.xsession
        sudo systemctl enable xrdp
        sudo systemctl start xrdp
        sudo ufw allow 3389

    - name: Set Password for Default User
      run: echo "ubuntu:toor123" | sudo chpasswd

    - name: Download & Run Playit
      run: |
        wget https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-linux-amd64 -O playit
        chmod +x playit
        nohup ./playit --secret "${{ secrets.PLAYIT_KEY }}" > playit.log 2>&1 &
        sleep 5
        cat playit.log

    - name: Keep Runner Alive
      run: sleep 10800
